### ISSUE TITLE
No Longer Connects to Tumblr

### ISSUE THREAD

**Issue by drmstwizard** [cubeghost/tagreplacer#30]
An error report comes back that says to contact the app maintainer, so this is me doing that. :) Good luck and thank you!!

**Comment by cubeghost** [comment]
hi, could you attach a screenshot of that report? could you also share your browser and operating system? it sounds like this is only happening for you

**Comment by drmstwizard** [comment]
Sure thing -- it fixed itself last night, but today it's popped up again. It pops up after prolonged use, if that helps!

![Image1](https://user-images.githubusercontent.com/29028771/147888890-ddbb879c-1f7c-48cc-b067-507f9c412353.png)

**Comment by cubeghost** [comment]
oh this is just the default error when my server goes down. this has been happening because i increased the number of web server workers recently so it can handle more connections, but as a result my server runs out of memory more frequently and gets rebooted. should usually go away after a few minutes
